name       : mkfontdir
version    : 1.0.7
release    : 4
source     :
    - http://xorg.freedesktop.org/releases/individual/app/mkfontdir-1.0.7.tar.bz2 : 56d52a482df130484e51fd066d1b6eda7c2c02ddbc91fe6e2be1b9c4e7306530
license    :
    - MIT
component  : xorg.apps
summary    : |
    X.Org Applications: mkfontdir
description: |
    X.Org Applications: mkfontdir
rundeps    :
    - mkfontscale
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
